[pytest]
pythonpath =
    methods/generation
    methods/evaluation
    methods/on_device
testpaths =
    methods/debug/generation_tests
    methods/debug/on_device_tests
    methods/evaluation/detection/tests
